language: csharp

os: linux # Ubuntu 14.04
dist: trusty
sudo: required
dotnet: 2.0.0

script:
  - dotnet restore || travis_terminate 1
  - dotnet build || travis_terminate 1
  - dotnet test test/GTFS.Tests || travis_terminate 1
  - "if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG ]]; then 
  dotnet pack src/GTFS --configuration Release /p:Version=$TRAVIS_TAG;
  dotnet nuget push src/GTFS/bin/Release/*.nupkg -s https://www.nuget.org/api/v2/package -k $NUGET_API_KEY;
  fi"